services:
  postgres:
    container_name: postgres-sql-roles
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: haythem
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: roles_permissions
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-roles
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025


networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local