server:
  port: 8050
  servlet:
    context-path: /api/v1/

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json
